name: deploy-nustore

on:
  push:
    branches: ['main']
    paths:
      - 'nustore/**'

defaults:
  run:
    working-directory: nustore

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy
        uses: chrislennon/action-aws-cli@v1.1

      - name: Deploy-Aws
        run: aws s3 sync dist s3://${{ secrets.AWS_BUCKET_NAME }}/nustore/latest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
